from guide_parser import GuideParser
# starting string must be unique without the '1. ' part!

parsers = {
    # # English Guides
    # "guide_art_1_eng": GuideParser(guide_id="guide_art_1_eng", remove_patterns=["Concepts of “jurisdiction” and imputability"]),
    # "guide_art_2_eng": GuideParser(guide_id="guide_art_2_eng"),
    # "guide_art_3_eng": GuideParser(guide_id="guide_art_3_eng", starting_string="1.  The Court’s approach to the interpretation"),
    # "guide_art_4_eng": GuideParser(guide_id="guide_art_4_eng"),
    # "guide_art_5_eng": GuideParser(guide_id="guide_art_5_eng"),
    # "guide_art_6_civil_eng": GuideParser(guide_id="guide_art_6_civil_eng"),
    # "guide_art_6_criminal_eng": GuideParser(guide_id="guide_art_6_criminal_eng"),
    # "guide_art_7_eng": GuideParser(guide_id="guide_art_7_eng", starting_string="1.  The guarantee enshrined in Article 7"),
    # "guide_art_8_eng": GuideParser(guide_id="guide_art_8_eng"),
    # "guide_art_9_eng": GuideParser(guide_id="guide_art_9_eng"),
    # "guide_art_10_eng": GuideParser(guide_id="guide_art_10_eng"),
    # "guide_art_11_eng": GuideParser(guide_id="guide_art_11_eng"),
    # "guide_art_12_eng": GuideParser(guide_id="guide_art_12_eng", starting_string="1.  Article 12 of the Convention guarantees"),
    # "guide_art_13_eng": GuideParser(guide_id="guide_art_13_eng"),
    # "guide_art_14_art_1_protocol_12_eng": GuideParser(guide_id="guide_art_14_art_1_protocol_12_eng"),
    # "guide_art_15_eng": GuideParser(guide_id="guide_art_15_eng"),
    # "guide_art_17_eng": GuideParser(guide_id="guide_art_17_eng"),
    # "guide_art_18_eng": GuideParser(guide_id="guide_art_18_eng"),
    # "Admissibility_guide_ENG": GuideParser(guide_id="Admissibility_guide_ENG", url="https://www.echr.coe.int/documents/d/echr/", starting_string="1.  The  system  of  protection  of  fundamental  rights"),
    # "guide_art_46_eng": GuideParser(guide_id="guide_art_46_eng", starting_string="1.  One of the most significant features of the Convention"),
    # "guide_art_1_protocol_1_eng": GuideParser(guide_id="guide_art_1_protocol_1_eng"),
    # "guide_art_2_protocol_1_eng": GuideParser(guide_id="guide_art_2_protocol_1_eng"),
    # "guide_art_3_protocol_1_eng": GuideParser(guide_id="guide_art_3_protocol_1_eng"),
    # "guide_art_2_protocol_4_eng": GuideParser(guide_id="guide_art_2_protocol_4_eng", starting_string="1.  Article 2 of Protocol No. 4 guarantees three"),
    # "guide_art_3_protocol_4_eng": GuideParser(guide_id="guide_art_3_protocol_4_eng", starting_string="1.  Article 3, Protocol No. 4 guarantees two"),
    # "guide_art_4_protocol_4_eng": GuideParser(guide_id="guide_art_4_protocol_4_eng"),
    # "guide_art_1_protocol_7_eng": GuideParser(guide_id="guide_art_1_protocol_7_eng", starting_string="1.  Protocol No. 7 to the European Convention"),
    # "guide_art_2_protocol_7_eng": GuideParser(guide_id="guide_art_2_protocol_7_eng", starting_string="1.  Article 2  of  Protocol  No.  7  complements  the  guarantees"),
    # "guide_art_4_protocol_7_eng": GuideParser(guide_id="guide_art_4_protocol_7_eng", starting_string="1.  Protocol No. 7 to the Convention"),
    # "guide_data_protection_eng": GuideParser(guide_id="guide_data_protection_eng", starting_string="1.  Technological progress has led to a quantum"),
    # "guide_environment_eng": GuideParser(guide_id="guide_environment_eng", starting_string="1.  The positive obligation on States to take"),
    # "guide_immigration_eng": GuideParser(guide_id="guide_immigration_eng", starting_string="1.  The present  document is"),
    # "guide_mass_protests_eng": GuideParser(guide_id="guide_mass_protests_eng", starting_string="1.  The  present  Guide  analyses  the  Court’s"),
    # "guide_prisoners_rights_eng": GuideParser(guide_id="guide_prisoners_rights_eng", starting_string="1.  The Court is frequently called upon to"),
    # "guide_lgbti_rights_eng": GuideParser(guide_id="guide_lgbti_rights_eng", starting_string="1.  The  Convention  is  a  living  instrument  which"),
    # "guide_social_rights_eng": GuideParser(guide_id="guide_social_rights_eng", starting_string="1.  The Convention as adopted in 1950 reflected"),
    # "guide_terrorism_eng": GuideParser(guide_id="guide_terrorism_eng", starting_string="1.   Since its first ever judgment Lawless v. Ireland"),
    
    # # Romanian Guides
    # "guide_art_1_ron": GuideParser(guide_id="guide_art_1_ron",),
    # "guide_art_2_ron": GuideParser(guide_id="guide_art_2_ron",),
    # "guide_art_3_ron": GuideParser(guide_id="guide_art_3_ron", starting_string="1. Abordarea Curții față"),
    # "guide_art_4_ron": GuideParser(guide_id="guide_art_4_ron"),
    # "guide_art_5_ron": GuideParser(guide_id="guide_art_5_ron", starting_string='1. Proclamând "dreptul',),
    # "guide_art_6_civil_ron": GuideParser(
    #     guide_id="guide_art_6_civil_ron",
    #     starting_string='1. Noțiunea "drepturi',
    #     replace_patterns=[
    #         (r"56\.\*În", "56. *În"),
    #         (r"68\.\*Exe", "68. *Exe"),
    #         (r"70\.\*Cere", "70. *Cere"),
    #         ("201Exemple", "201. Exemple"),
    #         (r"266 \*Instanțe", "266. *Instanțe"),
    #         (r"354\.\*Obser", "354. *Obser"),
    #         (r'444\*\. P', '444. *P'),
    #     ]
    # ),
    # "guide_art_6_criminal_ron": GuideParser(guide_id="guide_art_6_criminal_ron",
    #                                         starting_string="1. Principiul cheie care",),
    # "guide_art_7_ron": GuideParser(guide_id="guide_art_7_ron",),
    # "guide_art_8_ron": GuideParser(guide_id="guide_art_8_ron", starting_string="1. Pentru a invoca art. 8, un reclamant"),
    # "guide_art_9_ron": GuideParser(
    #     guide_id="guide_art_9_ron", replace_patterns=[
    #         (r"\#\#\#\#\ 131\. Curtea", "131. Curtea")
    #     ],
    # ),
    # "guide_art_10_ron": GuideParser(
    #     guide_id="guide_art_10_ron",
    #     starting_string="1. Jurisprudența amplă pe care organele de control al",
    #     replace_patterns=[
    #         (r"19\.\ În\ cauza", "\n19. În cauza"),
    #         (r"\ \ 28\.\ Curtea\ a", "28. Curtea a"),
    #     ]
    # ),
    # "guide_art_11_ron": GuideParser(guide_id="guide_art_11_ron"),
    # "guide_art_12_ron": GuideParser(
    #     guide_id="guide_art_12_ron",
    #     starting_string="1. Art. 12 din",
    #     replace_patterns=[("159", "19")]
    # ),
    # "guide_art_13_ron": GuideParser(
    #     guide_id="guide_art_13_ron",
    #     replace_patterns=[
    #         (r"24\.\*\*Organul", "24. **Organul"),
    #         (r"48\*\*Sfera", "48. **Sfera"),
    #         (r"\#\#\#\# 165\.", "165."),
    #     ]
    # ),
    # "guide_art_14_art_1_protocol_12_ron": GuideParser(
    #     guide_id="guide_art_14_art_1_protocol_12_ron",
    #     starting_string="1. Art. 14 din Convenție",
    #     replace_patterns=[
    #         (r"860\. În", "86. În"),
    #     ],
    # ),
    # "guide_art_15_ron": GuideParser(
    #     guide_id="guide_art_15_ron",
    #     replace_patterns=[(r"44\-50\.", "44-50 .")],
    # ),
    # "guide_art_17_ron": GuideParser(
    #     guide_id="guide_art_17_ron",
    #     remove_patterns=[r"\# \*\*Anexă\*\*[\s\S]*",]
    # ),
    # "guide_art_18_ron": GuideParser(guide_id="guide_art_18_ron"),
    # "admissibility_guide_ron": GuideParser(guide_id="admissibility_guide_ron", starting_string="1. Sistemul", 
    #                                        replace_patterns=[("136\.", "\n136.")],
    #                                        remove_patterns=[r'"Curtea poate[\s\S]*?procesuală\) \(34\)']),
    # "guide_art_46_ron": GuideParser(
    #     guide_id="guide_art_46_ron",
    #     starting_string="1. Una dintre cele",
    #     remove_patterns=[r"1\. Înaltele[\s\S]*?obligațiilor \(46-4\)",]
    # ),
    # "guide_art_1_protocol_1_ron": GuideParser(
    #     guide_id="guide_art_1_protocol_1_ron",
    #     replace_patterns=[(" 9.", "9."), ("202. În", "222. În")],
    #     remove_patterns=[r"Curtea Europeană a Drepturilor Omului \d*\/\d* Ultima actualizare: 30.04.2020\s{0,1}",]
    # ),
    # "guide_art_2_protocol_1_ron": GuideParser(guide_id="guide_art_2_protocol_1_ron"),
    # "guide_art_3_protocol_1_ron": GuideParser(guide_id="guide_art_3_protocol_1_ron"),
    # "guide_art_2_protocol_4_ron": GuideParser(guide_id="guide_art_2_protocol_4_ron", 
    #                                           starting_string="1. Art. 2 din Protocolul",
    #                                           remove_patterns=[r"\#\#\#\# \*\*Art\. 2[\s\S]*?Interes public"]),
    # "guide_art_3_protocol_4_ron": GuideParser(guide_id="guide_art_3_protocol_4_ron",
    #                                           starting_string="1. Art. 3 din Protocolul nr. 4 garantează",
    #                                           remove_patterns=[r"\#\#\#\# \*\*Art\. 3[\s\S]*?propria țară"],),
    # "guide_art_4_protocol_4_ron": GuideParser(guide_id="guide_art_4_protocol_4_ron"),
    # "guide_art_1_protocol_7_ron": GuideParser(guide_id="guide_art_1_protocol_7_ron",
    #                                           starting_string="1. Protocolul nr. 7",
    #                                           remove_patterns=[r'### \*\*Art\. 1 § 1 din Protocolul nr\. 7\*\*\n\n\"1[\s\S]*?ăin \(P7-1-1\)']),
    # "guide_art_2_protocol_7_ron": GuideParser(guide_id="guide_art_2_protocol_7_ron",
    #                                           starting_string="1. Art. 2 din Protocolul",),
    # "guide_art_4_protocol_7_ron": GuideParser(guide_id="guide_art_4_protocol_7_ron",
    #                                           starting_string="1. Protocolul nr. 7",),
    # "guide_data_protection_ron": GuideParser(guide_id="guide_data_protection_ron", 
    #                                          starting_string="1. Progresele",
    #                                          replace_patterns=[
    #                                              (r"1\. În ceea ce privește su", "73. În ceea ce privește su"),
    #                                              (r"28\. Într", "88. Într"),
    #                                              (r"35\. În cauza \*\[C", "95. În cauza *[C"),
    #                                              (r"2474\.", "247."),
    #                                              ],
    #                                          ),
    # "guide_environment_ron": GuideParser(guide_id="guide_environment_ron", 
    #                                      starting_string="1. Obligația pozitivă",
    #                                      replace_patterns=[
    #                                          (r"#### \*\*83\. Exemple:\*\*", "83. Exemple:"),
    #                                          (r"#### 107\*\*\. Exemple:\*\*", "107. Exemple:"),
    #                                          (r'#### 121\*\*\. Exemple:\*\*', "121. Exemple:"),
    #                                          (r'#### 124\. \*\*Exemple:\*\*', "124. Exemple:"),
    #                                          (r'128\*\*\. Exemple:\*\*', "\n128. Exemple:"),
    #                                          ],
    #                                      remove_patterns=[
    #                                          r'### \*\*Art\. 46 din Convenție\*\*[\s\S]*?executării\. "',
    #                                          r'### \\\*\\\*\\\*\\\*\\\*\\\*\\\*[\s\S]*',
    #                                      ],
    #                                          ),
    # "guide_immigration_ron": GuideParser(guide_id="guide_immigration_ron",
    #                                      starting_string="1. Prezentul",
    #                                      remove_patterns=[
    #                                          r'"Înaltele[\s\S]*?interzise."',
    #                                      ],
    #                                      ),
    # "guide_mass_protests_ron": GuideParser(guide_id="guide_mass_protests_ron",
    #                                        starting_string="1. Prezentul",
    #                                        ),
    # "guide_prisoners_rights_ron": GuideParser(guide_id="guide_prisoners_rights_ron",
    #                                           starting_string="1. Curtea este",
    #                                               ),
    # "guide_lgbti_rights_ron": GuideParser(guide_id="guide_lgbti_rights_ron",
    #                                       starting_string="1. Convenția este",
    #                                       replace_patterns=[
    #                                             (r"142\.", "142. "),
    #                                             ],
    #                                       remove_patterns=[
    #                                           r'"Nimeni nu poate[\s\S]*?situație\."',
    #                                           ],
    #                                           ),
    # "guide_social_rights_ron": GuideParser(guide_id="guide_social_rights_ron",
    #                                        starting_string="1. Convenția europeană",
    #                                        replace_patterns=[
    #                                            (r'111\. Î', '11. Î'),
    #                                            (r'176\.', '\n176.'),
    #                                            (r'199\.', '\n199.'),
    #                                        ],
    #                                        ),
    # "guide_terrorism_ron": GuideParser(guide_id="guide_terrorism_ron",
    #                                    starting_string="1. Chiar de la prima",
    #                                    ),
    # "guide_rights_of_the_child_ron": GuideParser(guide_id="guide_rights_of_the_child_ron",
    #                                              starting_string="1. Deși doar"),
    # "guide_eu_law_in_echr_case-law_ron": GuideParser(guide_id="guide_eu_law_in_echr_case-law_ron",
    #                                                  starting_string="1. Prezentul",
    #                                                  replace_patterns=[
    #                                                      (r'\n4\. Cur', '\n 4. Cur'),
    #                                                  ],
    #                                                  ),


    # French Guides
    "guide_art_1_fre": GuideParser(guide_id="guide_art_1_fre",),
    "guide_art_2_fre": GuideParser(guide_id="guide_art_2_fre",),
    "guide_art_3_fre": GuideParser(guide_id="guide_art_3_fre", starting_string="1. La Cour doit guider son"),
    "guide_art_5_fre": GuideParser(guide_id="guide_art_5_fre",),
    "guide_art_6_civil_fre": GuideParser(guide_id="guide_art_6_civil_fre",),
    "guide_art_6_criminal_fre": GuideParser(guide_id="guide_art_6_criminal_fre",),
    "guide_art_7_fre": GuideParser(guide_id="guide_art_7_fre",),
    "guide_art_8_fre": GuideParser(guide_id="guide_art_8_fre",),
    "guide_art_9_fre": GuideParser(guide_id="guide_art_9_fre",),
    "guide_art_10_fre": GuideParser(guide_id="guide_art_10_fre",),
    "guide_art_11_fre": GuideParser(guide_id="guide_art_11_fre",),
    "guide_art_12_fre": GuideParser(guide_id="guide_art_12_fre", starting_string="1. L'article 12 de la Convention"),
    "guide_art_13_fre": GuideParser(guide_id="guide_art_13_fre",),
    "guide_art_14_art_1_protocol_12_fre": GuideParser(guide_id="guide_art_14_art_1_protocol_12_fre", starting_string="1. L'article 14 de la Convention consacre la protection"),
    "guide_art_15_fre": GuideParser(guide_id="guide_art_15_fre",),
    "guide_art_17_fre": GuideParser(guide_id="guide_art_17_fre",),
    "guide_art_18_fre": GuideParser(guide_id="guide_art_18_fre",),
    "guide_art_46_fre": GuideParser(guide_id="guide_art_46_fre", starting_string="1. L'un des traits les plus significatifs du", remove_patterns=[r"« 1\. Les Hautes[\s\S]*manquement \(46-4\)"]),
    "guide_data_protection_fre": GuideParser(guide_id="guide_data_protection_fre", starting_string="1. Les avancées technologiques repoussent"),
    "guide_environment_fre": GuideParser(guide_id="guide_environment_fre", starting_string="1. La juridiction d'un État, au sens"),
    "guide_immigration_fre": GuideParser(guide_id="guide_immigration_fre", starting_string="1. Le présent document a"),
    "guide_mass_protests_fre": GuideParser(guide_id="guide_mass_protests_fre", starting_string="1. Le présent guide offre une analyse de"),
    "guide_prisoners_rights_fre": GuideParser(guide_id="guide_prisoners_rights_fre",),
    "guide_lgbti_rights_fre": GuideParser(guide_id="guide_lgbti_rights_fre",),
    "guide_social_rights_fre": GuideParser(guide_id="guide_social_rights_fre",),
    "guide_terrorism_fre": GuideParser(guide_id="guide_terrorism_fre",),
    "guide_rights_of_the_child_fre": GuideParser(guide_id="guide_rights_of_the_child_fre",),
    "guide_eu_law_in_echr_case-law_fre": GuideParser(guide_id="guide_eu_law_in_echr_case-law_fre",),
}



# From citations:

#     # Romanian Guides
#     "guide_art_1_ron": GuideParser(guide_id="guide_art_1_ron", remove_patterns=[r"Curtea Europeană a Drepturilor Omului\s+[\s\n]*\d+\/\d+\s+Actualizare: \d{2}\.\d{2}\.\s*\d{4}[\s\n]*(.*?)\n(.*?)\n",]),
#     "guide_art_2_ron": GuideParser(guide_id="guide_art_2_ron",),
#     "guide_art_3_ron": GuideParser(guide_id="guide_art_3_ron", starting_string="1.  Abordarea Curții față"),
#     "guide_art_4_ron": GuideParser(guide_id="guide_art_4_ron"),
#     "guide_art_5_ron": GuideParser(guide_id="guide_art_5_ron", starting_string="1.  Proclamând „dreptul la libertate”, art. 5 § 1 vizează"),
#     # "guide_art_6_civil_ron": GuideParser(guide_id="guide_art_6_civil_ron", starting_string="1.  Noțiunea „drepturi și obligații cu caracter civil”"),
#     "guide_art_7_ron": GuideParser(guide_id="guide_art_7_ron"),
#     # "guide_art_8_ron": GuideParser(guide_id="guide_art_8_ron"),
#     # "guide_art_9_ron": GuideParser(guide_id="guide_art_9_ron"),
#     # "guide_art_10_ron": GuideParser(guide_id="guide_art_10_ron", starting_string="1. Jurisprudența amplă pe care organele de control al"),
#     # "guide_art_11_ron": GuideParser(guide_id="guide_art_11_ron"),
#     # "guide_art_12_ron": GuideParser(guide_id="guide_art_12_ron", starting_string="1. Art. 12 din Convenție garantează"),
#     # "guide_art_13_ron": GuideParser(guide_id="guide_art_13_ron"),
#     # "guide_art_14_art_1_protocol_12_ron": GuideParser(guide_id="guide_art_14_art_1_protocol_12_ron", starting_string="1. Art. 14 din Convenție consacră protecția împotriva"),
#     # "guide_art_15_ron": GuideParser(guide_id="guide_art_15_ron"),
#     # "guide_art_17_ron": GuideParser(guide_id="guide_art_17_ron"),
#     # "guide_art_18_ron": GuideParser(guide_id="guide_art_18_ron"),
#     # "guide_art_46_ron": GuideParser(guide_id="guide_art_46_ron", starting_string="1. Una dintre cele mai importante caracteristici"), #todo
